CREATE TABLE IF NOT EXISTS academic_years (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  semester VARCHAR(20) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'Mendatang',
  total_courses INT NOT NULL DEFAULT 0,
  total_students INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS courses (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  instructor VARCHAR(255) NOT NULL,
  assistant VARCHAR(255) NOT NULL,
  study_program VARCHAR(255) NOT NULL DEFAULT 'Teknik Informatika',
  academic_year VARCHAR(100) NOT NULL DEFAULT 'Genap 2024/2025',
  class_code VARCHAR(50) NOT NULL DEFAULT '',
  status VARCHAR(20) NOT NULL DEFAULT 'Aktif',
  day VARCHAR(50) NOT NULL DEFAULT '',
  start_time VARCHAR(10) NOT NULL DEFAULT '',
  end_time VARCHAR(10) NOT NULL DEFAULT '',
  room VARCHAR(100) NOT NULL DEFAULT '',
  sessions INT NOT NULL DEFAULT 14 CHECK (sessions > 0),
  credits INT NOT NULL DEFAULT 3 CHECK (credits > 0),
  students INT NOT NULL DEFAULT 0 CHECK (students >= 0),
  attendance_present INT NOT NULL DEFAULT 0,
  attendance_total INT NOT NULL DEFAULT 12,
  color VARCHAR(50) NOT NULL DEFAULT 'bg-blue-500',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS assignments (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  course VARCHAR(255) NOT NULL,
  assistant VARCHAR(255) NOT NULL,
  due_date VARCHAR(50) NOT NULL,
  due_time VARCHAR(10) NOT NULL DEFAULT '23:59',
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','submitted','graded')),
  course_color VARCHAR(50) NOT NULL DEFAULT 'bg-blue-500',
  submitted_date VARCHAR(50),
  score INT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS grades (
  id SERIAL PRIMARY KEY,
  course_name VARCHAR(255) NOT NULL,
  code VARCHAR(50) NOT NULL,
  semester VARCHAR(50) NOT NULL,
  credits INT NOT NULL CHECK (credits > 0),
  grade VARCHAR(5) NOT NULL,
  score INT NOT NULL CHECK (score >= 0 AND score <= 100),
  color VARCHAR(50) NOT NULL DEFAULT 'bg-blue-500',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS students (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  default_password VARCHAR(255) NOT NULL,
  student_id VARCHAR(50) NOT NULL UNIQUE,
  program VARCHAR(255) NOT NULL,
  semester INT NOT NULL CHECK (semester > 0),
  courses TEXT[] NOT NULL DEFAULT '{}',
  status VARCHAR(50) NOT NULL DEFAULT 'Aktif',
  join_date DATE NOT NULL DEFAULT CURRENT_DATE,
  is_password_changed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lecturers (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL DEFAULT 'password',
  default_password VARCHAR(255) NOT NULL DEFAULT 'password',
  nidn VARCHAR(50) NOT NULL UNIQUE,
  courses TEXT[] NOT NULL DEFAULT '{}',
  is_password_changed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lab_assistants (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(50) NOT NULL DEFAULT '',
  student_id VARCHAR(50) NOT NULL UNIQUE,
  lab VARCHAR(255) NOT NULL,
  supervisor VARCHAR(255) NOT NULL DEFAULT '',
  semester INT NOT NULL DEFAULT 1,
  gpa NUMERIC(3,2) NOT NULL DEFAULT 0,
  assigned_courses INT NOT NULL DEFAULT 0,
  weekly_hours INT NOT NULL DEFAULT 0,
  status VARCHAR(50) NOT NULL DEFAULT 'Aktif',
  join_date DATE NOT NULL DEFAULT CURRENT_DATE,
  password VARCHAR(255) NOT NULL DEFAULT 'password',
  default_password VARCHAR(255) NOT NULL DEFAULT 'password',
  is_password_changed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS classes (
  id SERIAL PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  academic_year VARCHAR(50) NOT NULL,
  assistant VARCHAR(255) NOT NULL DEFAULT '',
  schedule VARCHAR(255) NOT NULL DEFAULT '',
  room VARCHAR(100) NOT NULL DEFAULT '',
  total_students INT NOT NULL DEFAULT 0,
  capacity INT NOT NULL CHECK (capacity > 0),
  students INT[] NOT NULL DEFAULT '{}',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
